### ISSUE TITLE
Problem with picking integration

### ISSUE THREAD

**Issue by tmwden** [MTrab/clever#4]
Hi Malene

Thanks alot for creating integration for Clever :-)
I am not a developer, and i just created my github account, so please bear with me for any mistakes....

I have added the files to custom_components, i can see "clever" in the integrations list, however i get this error :
![image](https://user-images.githubusercontent.com/37026374/204132391-173d29a1-291a-41c0-9502-eaccccbb150f.png)

Best regards

Thomas

**Comment by MTrab** [comment]
Confirmed - fix will be up in a moment
