### ISSUE TITLE
Kun en stander eller

### ISSUE THREAD

**Issue by knudhamm** [MTrab/clever#6]
Kan der være en lille fejl. 
Jeg får kun vist et sted i f.eks. Roskilde. 
Burde jeg ikke få alle steder i Roskilde, hvor der er mulighed for opladning?
![l1](https://user-images.githubusercontent.com/111384669/204138306-856ecdbc-4add-4409-a708-879b6c92ae64.jpg)
![l2](https://user-images.githubusercontent.com/111384669/204138311-c48b063d-f7aa-48e7-89bf-eba56e17135c.jpg)
![l3](https://user-images.githubusercontent.com/111384669/204138317-1cd00b52-6d97-469f-b942-df36ad0fd65d.jpg)

**Comment by MTrab** [comment]
Du vælger jo et specifikt ladested.
Skal du have flere, skal du bare tilføje integrationen igen, men med en anden stander.

**Comment by knudhamm** [comment]
Selvfølgelig. Det er nu afprøvet og virker perfekt. Tusind tak.
