### ISSUE TITLE
Optaget stander ud af antal.

### ISSUE THREAD

**Issue by knudhamm** [MTrab/clever#7]
Det kunne være rigtig fint, hvis der var mulighed for at se, hvor mange stander der var i alt - som på Ladekortet.
Den viser f.eks. hvor mange der er optaget, men ikke ud af hvor mange. Nice to have :-).
![l4](https://user-images.githubusercontent.com/111384669/204143941-fc1f0645-236c-427a-a3a0-7bdf782b7c61.jpg)
![l5](https://user-images.githubusercontent.com/111384669/204143947-2fbb5952-4933-4bdf-9a7e-fd88d530838f.jpg)

**Comment by MTrab** [comment]
Det er i attributes - det er lidt med vilje, da det er svært at lave noget automatisering ud fra 6/8 som state ;)

**Comment by knudhamm** [comment]
Det så fint. Så snupper jeg det derfra :-).
